/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 BOTELLA_ARTIC.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BOTELLA_ARTIC.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[0, 0.295, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Default(98FD495A-7D19-4160-BD9B-C4322F3BBCAF)'].geometry} material={materials['Soft Textured Black #1']} />
          <mesh geometry={nodes['Default(EA40679E-F627-4B18-8CAA-C8924236593C)'].geometry} material={materials['Liquid Water Bubbles #1']} />
          <mesh geometry={nodes['Default(9010FB83-7752-4448-B70D-4274F7C46523)'].geometry} material={materials['Liquid Water Bubbles #1']} />
          <mesh geometry={nodes['Default(9132A971-869A-4385-8DF0-A382E1FC651F)'].geometry} material={materials['Glass (Solid) White #2']} />
          <mesh geometry={nodes['Default(973A27FD-2A31-4991-984B-04D8645A9456)'].geometry} material={materials['Glass (Solid) White #1']} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={730.837} near={550.219} fov={32.644} position={[0.028, 0.371, 0.594]} rotation={[-0.365, 0.025, 0.009]} scale={0.001} />
      <PerspectiveCamera makeDefault={false} far={1581.342} near={1412.574} fov={48.174} position={[0.943, -0.076, 1.169]} rotation={[0.248, 0.822, -0.183]} scale={0.001} />
      <OrthographicCamera makeDefault={false} far={328.662} near={62.595} position={[-0.021, 0.329, -0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <OrthographicCamera makeDefault={false} far={251.105} near={161.803} position={[0.003, 0.015, 0.206]} scale={0.001} />
      <OrthographicCamera makeDefault={false} far={497.441} near={408.079} position={[0.453, -0.175, -0.447]} rotation={[0, Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/BOTELLA_ARTIC.gltf')
